package: cloud.lazycat.app.rainloop
version: 0.18.0
name: rainloop
description: "简洁,现代化&快捷的基于网络的邮件客户端"
min_os_version: "1.5.0"
homepage: https://hub.docker.com/r/amwpfiqvy/rainloop
author: amwpfiqvy
locales:
  zh:
    description: "简洁,现代化&快捷的基于网络的邮件客户端"
    name: rainloop
  en:
    description: "Simple, modern & fast web-based email client"
    name: rainloop
